return {
  "folke/which-key.nvim",
  opts = {
    spec = {
      { "<leader>ci", group = "compiler", icon = " " },
      { "<leader>k", group = "toolkit", icon = "󱁤" },
      { "<leader>kp", group = "preview", icon = "" },
      { "<leader>kt", group = "leetcode", icon = "󰩐" },
      { "<leader>o", group = "overseer", icon = " " },
      { "<leader>r", group = "backend", icon = " " },
      { "<leader>rr", group = "kulala", icon = " " },
      { "<leader>rs", group = "spring", icon = " " },
      { "<leader>y", icon = "󰇥" },
      { "<leader>Y", icon = "󰇥" },
      -- Hide disabled / unwanted keys
      { "<leader>D", hidden = true },
      { "<leader>e", hidden = true },
      { "<leader>E", hidden = true },
      { "<leader>K", hidden = true },
      { "<leader>L", hidden = true },
      { "<leader>-", hidden = true },
      { "<leader>`", hidden = true },
      { "<leader>|", hidden = true },
      { "<leader>cd", hidden = true },
      { "<C-w><C-d>", hidden = true },
      { "<leader>d2", hidden = true },
      { "<leader>rd2", hidden = true },
      { "<leader>yd2", hidden = true },
    },
  },
}
